Repository chunky-dev/chunky, pull requests merged in 2021-03, with the labels that each got.

#835 Picture export API
  chunky/src/java/se/llbit/chunky/main/Chunky.java
  chunky/src/java/se/llbit/chunky/renderer/OutputMode.java
  chunky/src/java/se/llbit/chunky/renderer/export/PfmExportFormat.java
  chunky/src/java/se/llbit/chunky/renderer/export/PictureExportFormat.java
  chunky/src/java/se/llbit/chunky/renderer/export/PictureExportFormats.java
  chunky/src/java/se/llbit/chunky/renderer/export/PngExportFormat.java
  chunky/src/java/se/llbit/chunky/renderer/export/Tiff32ExportFormat.java
  chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
  chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java
  chunky/src/java/se/llbit/chunky/ui/render/AdvancedTab.java
Labels: Plugin API

#845 Corrected spelling error: lense shift
  chunky/src/java/se/llbit/chunky/ui/render/CameraTab.java
  chunky/src/res/se/llbit/chunky/ui/render/CameraTab.fxml
Labels: GUI

#846 21w10a
  chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
  chunky/src/java/se/llbit/chunky/resources/Texture.java
  chunky/src/java/se/llbit/chunky/resources/TexturePackLoader.java
Labels: chunky 2.x, minecraft

#847 Minor optimisations 2
  chunky/src/java/se/llbit/chunky/map/WorldMapLoader.java
  chunky/src/java/se/llbit/chunky/world/WorldTexture.java
  chunky/src/java/se/llbit/math/Octree.java
  chunky/src/java/se/llbit/math/PackedOctree.java
Labels: performance

#849 Return non-zero exit codes on errors
  chunky/src/java/se/llbit/chunky/main/Chunky.java
  chunky/src/java/se/llbit/chunky/main/CommandLineOptions.java
Labels: bug, headless mode

#850 Improve scene chooser for scenes with backup files
  chunky/src/java/se/llbit/chunky/main/SceneHelper.java
  chunky/src/java/se/llbit/chunky/ui/SceneChooserController.java
Labels: GUI

#851 Fix octree shifting by storing yMin and yMax in the scene file.
  chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
Labels: bug, chunky 2.x, snapshot-only

#857 21w11a
  chunky/src/java/se/llbit/chunky/block/CaveVines.java
  chunky/src/java/se/llbit/chunky/block/LightningRod.java
  chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
  chunky/src/java/se/llbit/chunky/block/SmallDripleaf.java
  chunky/src/java/se/llbit/chunky/chunk/BlockPalette.java
  chunky/src/java/se/llbit/chunky/entity/Lectern.java
  chunky/src/java/se/llbit/chunky/model/LightningRodModel.java
  chunky/src/java/se/llbit/chunky/model/SmallDripleafModel.java
  chunky/src/java/se/llbit/chunky/resources/Texture.java
  chunky/src/java/se/llbit/chunky/resources/TexturePackLoader.java
Labels: minecraft

#852 Fix water chunk border finalization
  chunky/src/java/se/llbit/chunky/renderer/scene/OctreeFinalizer.java
  chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
Labels: bug, snapshot-only

#858 Fix null pointer exception when chunk loading times out.
  chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
Labels: bug, snapshot-only

#859 Improve scene loading speed drastically.
  chunky/src/java/se/llbit/chunky/renderer/renderdump/FloatingPointCompressor.java
  chunky/src/java/se/llbit/chunky/renderer/renderdump/RenderDump.java
  chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
  chunky/src/java/se/llbit/chunky/resources/OctreeFileFormat.java
  chunky/src/java/se/llbit/chunky/world/ChunkDataSource.java
  chunky/src/java/se/llbit/math/Octree.java
Labels: performance
