Repository chunky-dev/chunky, pull requests merged in 2021-10, with the labels that each got.

#1044 Fix parallel projection autofocus
  chunky/src/java/se/llbit/chunky/renderer/projection/ParallelProjector.java
  chunky/src/java/se/llbit/chunky/renderer/scene/Camera.java
  chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
Labels: bug, hacktoberfest-accepted

#1051 Fix Target SPP slider.
  lib/src/se/llbit/chunky/ui/SliderAdjuster.java
Labels: hacktoberfest-accepted

#1048 Fix CPU load setting.
  chunky/src/java/se/llbit/chunky/renderer/DefaultRenderManager.java
  chunky/src/java/se/llbit/chunky/renderer/RenderWorkerPool.java
Labels: hacktoberfest-accepted

#1045 Terminal interaction copyright notice.
  chunky/src/java/se/llbit/chunky/main/CommandLineOptions.java
Labels: headless mode, hacktoberfest-accepted

#1052 Allow negative numbers as command line arguments in options
  chunky/src/java/se/llbit/chunky/main/CommandLineOptions.java
  chunky/src/test/se/llbit/chunky/main/OptionHandlerTest.java
Labels: hacktoberfest-accepted
