Repository chunky-dev/chunky, pull requests merged in 2021-09, with the labels that each got.

#1025 Move render controls UI
  chunky/src/res/se/llbit/chunky/ui/Chunky.fxml
Labels: GUI

#1014 Deselect Chunks In Rectangle If All Selected
  chunky/src/java/se/llbit/chunky/ui/ChunkMap.java
  chunky/src/java/se/llbit/chunky/world/ChunkSelectionTracker.java
Labels: GUI

#1037 Show a hint in the render tab if no chunks are loaded.
  chunky/src/java/se/llbit/chunky/ui/RenderCanvasFx.java
Labels: GUI

#1031 Add CubicChunks support
  chunky/src/java/se/llbit/chunky/map/MapTile.java
  chunky/src/java/se/llbit/chunky/map/MapView.java
  chunky/src/java/se/llbit/chunky/map/SurfaceLayer.java
  chunky/src/java/se/llbit/chunky/map/WorldMapLoader.java
  chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
  chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java
  chunky/src/java/se/llbit/chunky/world/Chunk.java
  chunky/src/java/se/llbit/chunky/world/ChunkView.java
  chunky/src/java/se/llbit/chunky/world/CubicWorld.java
  chunky/src/java/se/llbit/chunky/world/DeleteChunksJob.java
  chunky/src/java/se/llbit/chunky/world/EmptyChunk.java
  chunky/src/java/se/llbit/chunky/world/EmptyRegionChunk.java
  chunky/src/java/se/llbit/chunky/world/ImposterCubicChunk.java
  chunky/src/java/se/llbit/chunky/world/World.java
  chunky/src/java/se/llbit/chunky/world/region/CubicRegionChangeWatcher.java
  chunky/src/java/se/llbit/chunky/world/region/EmptyRegion.java
  chunky/src/java/se/llbit/chunky/world/region/ImposterCubicRegion.java
  chunky/src/java/se/llbit/chunky/world/region/MCRegion.java
  chunky/src/java/se/llbit/chunky/world/region/MCRegionChangeWatcher.java
  chunky/src/java/se/llbit/chunky/world/region/Region.java
  chunky/src/java/se/llbit/chunky/world/region/RegionChangeWatcher.java
  chunky/src/java/se/llbit/chunky/world/region/RegionParser.java
  chunky/src/java/se/llbit/chunky/world/region/RegionQueue.java
  chunky/src/res/se/llbit/chunky/ui/Chunky.fxml
  lib/src/se/llbit/util/Mutable.java
Labels: feature request

#1032 Simple map view optimisations
  chunky/src/java/se/llbit/chunky/block/legacy/LegacyBlocks.java
  chunky/src/java/se/llbit/chunky/map/SurfaceLayer.java
  chunky/src/java/se/llbit/chunky/world/Chunk.java
  chunky/src/java/se/llbit/chunky/world/CubicWorld.java
  chunky/src/java/se/llbit/chunky/world/ImposterCubicChunk.java
  chunky/src/java/se/llbit/chunky/world/World.java
Labels: performance
