Repository chunky-dev/chunky, pull requests merged in 2021-12, with the labels that each got.

#1078 Basic support of the new block data location in 1.18
  chunky/src/java/se/llbit/chunky/world/Chunk.java
  chunky/src/java/se/llbit/util/NbtUtil.java
Labels: minecraft, backport-me

#1083 Fix regression when loading pre-1.18 worlds.
  chunky/src/java/se/llbit/chunky/world/Chunk.java
Labels: snapshot-only

#1091 Download skin from API if the skin cache file is not found.
  chunky/src/java/se/llbit/chunky/entity/PlayerEntity.java
Labels: backport-me

#1101 Fix scene tab scroll
  chunky/src/java/se/llbit/chunky/ui/render/GeneralTab.java
Labels: bug, GUI, backport-me

#1104 Fix six-sided wood blocks in pre-1.13 worlds.
  chunky/src/java/se/llbit/chunky/block/legacy/LegacyBlocks.java
Labels: bug, backport-me

#1080 Implement release channels in the launcher.
  chunky/src/java/se/llbit/chunky/main/CommandLineOptions.java
  chunky/src/java/se/llbit/chunky/ui/CreditsController.java
  chunky/src/res/se/llbit/chunky/ui/Credits.fxml
  launcher/build.gradle
  launcher/src/se/llbit/chunky/launcher/ChunkyLauncher.java
  launcher/src/se/llbit/chunky/launcher/LauncherInfo.java
  launcher/src/se/llbit/chunky/launcher/LauncherInfoChecker.java
  launcher/src/se/llbit/chunky/launcher/UpdateChecker.java
  launcher/src/se/llbit/chunky/launcher/ui/ChunkyLauncher.fxml
  launcher/src/se/llbit/chunky/launcher/ui/ChunkyLauncherController.java
  launcher/src/se/llbit/chunky/launcher/ui/ChunkyLauncherFx.java
  launcher/src/se/llbit/chunky/launcher/ui/LauncherUpdateDialog.fxml
  launcher/src/se/llbit/chunky/launcher/ui/LauncherUpdateDialog.java
  launcher/src/se/llbit/chunky/launcher/ui/LauncherUpdateDialogController.java
  lib/src/se/llbit/chunky/launcher/LauncherSettings.java
  lib/src/se/llbit/chunky/launcher/ReleaseChannel.java
  lib/src/se/llbit/fxutil/CustomizedListCellFactory.java
Labels: launcher

#1105 Show the actual version next to "latest" in the version dropdown.
  launcher/src/se/llbit/chunky/launcher/ui/ChunkyLauncherController.java
Labels: launcher

#1108 Fix launcher release channel upgrade
  launcher/src/se/llbit/chunky/launcher/ChunkyLauncher.java
  launcher/src/se/llbit/chunky/launcher/LauncherInfoChecker.java
  launcher/src/se/llbit/chunky/launcher/UpdateChecker.java
  lib/src/se/llbit/chunky/launcher/LauncherSettings.java
Labels: bug, launcher

#1112 Fix scene renaming not switching the directory.
  chunky/src/java/se/llbit/chunky/renderer/scene/SynchronousSceneManager.java
Labels: bug, snapshot-only, backport-me
