Repository chunky-dev/chunky, pull requests merged in 2021-05, with the labels that each got.

#919 Improve numeric fields
  chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java
  chunky/src/java/se/llbit/chunky/ui/render/CameraTab.java
  chunky/src/java/se/llbit/chunky/ui/render/EntitiesTab.java
  chunky/src/java/se/llbit/chunky/ui/render/GeneralTab.java
  chunky/src/res/se/llbit/chunky/ui/Chunky.fxml
  chunky/src/res/se/llbit/chunky/ui/render/CameraTab.fxml
  chunky/src/res/style.css
  lib/src/se/llbit/chunky/ui/Adjuster.java
  lib/src/se/llbit/chunky/ui/DoubleTextField.java
  lib/src/se/llbit/chunky/ui/IntegerTextField.java
  lib/src/se/llbit/chunky/ui/NumericTextField.java
  lib/src/se/llbit/chunky/ui/SilentNumberStringConverter.java
Labels: GUI

#920 correct isBlockOnEdge checks
  chunky/src/java/se/llbit/chunky/chunk/SimpleChunkData.java
  chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
Labels: bug, snapshot-only

#890 RegionParser only clears chunk data if modified
  chunky/src/java/se/llbit/chunky/world/Chunk.java
  chunky/src/java/se/llbit/chunky/world/EmptyChunk.java
  chunky/src/java/se/llbit/chunky/world/EmptyRegionChunk.java
  chunky/src/java/se/llbit/chunky/world/RegionParser.java
Labels: performance

#941 Facing tooltip.
  chunky/src/java/se/llbit/chunky/renderer/scene/Camera.java
  chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
Labels: GUI

#940 Save the window position/size on close and restore that on startup
  chunky/src/java/se/llbit/chunky/ui/ChunkyFx.java
  lib/src/se/llbit/chunky/PersistentSettings.java
  lib/src/se/llbit/fxutil/WindowPosition.java
Labels: GUI

#947 Prevent empty scene creation
  chunky/src/java/se/llbit/chunky/ui/ChunkMap.java
  chunky/src/java/se/llbit/chunky/ui/render/GeneralTab.java
  chunky/src/res/style.css
Labels: GUI

#949 Postprocessing plugin api
  chunky/src/java/se/llbit/chunky/renderer/RenderManager.java
  chunky/src/java/se/llbit/chunky/renderer/RenderWorker.java
  chunky/src/java/se/llbit/chunky/renderer/postprocessing/ACESFilmicFilter.java
  chunky/src/java/se/llbit/chunky/renderer/postprocessing/GammaCorrectionFilter.java
  chunky/src/java/se/llbit/chunky/renderer/postprocessing/HableToneMappingFilter.java
  chunky/src/java/se/llbit/chunky/renderer/postprocessing/NoneFilter.java
  chunky/src/java/se/llbit/chunky/renderer/postprocessing/PixelPostProcessingFilter.java
  chunky/src/java/se/llbit/chunky/renderer/postprocessing/PostProcessingFilter.java
  chunky/src/java/se/llbit/chunky/renderer/postprocessing/PostProcessingFilters.java
  chunky/src/java/se/llbit/chunky/renderer/postprocessing/PreviewFilter.java
  chunky/src/java/se/llbit/chunky/renderer/postprocessing/SimplePixelPostProcessingFilter.java
  chunky/src/java/se/llbit/chunky/renderer/postprocessing/Tonemap1Filter.java
  chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
  chunky/src/java/se/llbit/chunky/ui/render/PostprocessingTab.java
  chunky/src/java/se/llbit/tiff/TiffFileWriter.java
  chunky/src/res/se/llbit/chunky/ui/render/PostprocessingTab.fxml
Labels: Plugin API

#950 Fix parsing skull textures that are not valid json (again)
  chunky/src/java/se/llbit/chunky/block/Head.java
  chunky/src/test/se/llbit/chunky/block/SkullTextureTest.java
Labels: bug

#918 Refactor render manager and add better support for rendering plugins.
  chunky/src/java/se/llbit/chunky/main/Chunky.java
  chunky/src/java/se/llbit/chunky/renderer/AbstractRenderManager.java
  chunky/src/java/se/llbit/chunky/renderer/DefaultRenderManager.java
  chunky/src/java/se/llbit/chunky/renderer/PathTracingRenderer.java
  chunky/src/java/se/llbit/chunky/renderer/PreviewRenderer.java
  chunky/src/java/se/llbit/chunky/renderer/RenderContext.java
  chunky/src/java/se/llbit/chunky/renderer/RenderController.java
  chunky/src/java/se/llbit/chunky/renderer/RenderManager.java
  chunky/src/java/se/llbit/chunky/renderer/RenderManagerFactory.java
  chunky/src/java/se/llbit/chunky/renderer/RenderTile.java
  chunky/src/java/se/llbit/chunky/renderer/RenderWorker.java
  chunky/src/java/se/llbit/chunky/renderer/RenderWorkerPool.java
  chunky/src/java/se/llbit/chunky/renderer/Renderer.java
  chunky/src/java/se/llbit/chunky/renderer/TileBasedRenderer.java
  chunky/src/java/se/llbit/chunky/renderer/scene/AsynchronousSceneManager.java
  chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
  chunky/src/java/se/llbit/chunky/renderer/scene/SynchronousSceneManager.java
  chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java
  chunky/src/java/se/llbit/chunky/ui/RenderCanvasFx.java
  chunky/src/java/se/llbit/chunky/ui/RenderControlsFxController.java
  chunky/src/java/se/llbit/chunky/ui/render/AdvancedTab.java
  chunky/src/java/se/llbit/util/Registerable.java
  chunky/src/res/se/llbit/chunky/ui/render/AdvancedTab.fxml
  chunky/src/test/se/llbit/chunky/main/PluginApiTest.java
  chunky/src/test/se/llbit/chunky/renderer/TestBlankRender.java
  chunky/src/test/se/llbit/chunky/renderer/TestDeadlock.java
Labels: Plugin API, renderer

#938 Add support for Minecraft 1.12 or older worlds
  README.md
  chunky/src/java/se/llbit/chunky/block/Block.java
  chunky/src/java/se/llbit/chunky/block/BlockFace.java
  chunky/src/java/se/llbit/chunky/block/BlockProvider.java
  chunky/src/java/se/llbit/chunky/block/BlockSpec.java
  chunky/src/java/se/llbit/chunky/block/Comparator.java
  chunky/src/java/se/llbit/chunky/block/Door.java
  chunky/src/java/se/llbit/chunky/block/EnderChest.java
  chunky/src/java/se/llbit/chunky/block/FenceGate.java
  chunky/src/java/se/llbit/chunky/block/FinalizationState.java
  chunky/src/java/se/llbit/chunky/block/Glass.java
  chunky/src/java/se/llbit/chunky/block/Grass.java
  chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
  chunky/src/java/se/llbit/chunky/block/OctreeFinalizationState.java
  chunky/src/java/se/llbit/chunky/block/Repeater.java
  chunky/src/java/se/llbit/chunky/block/Sign.java
  chunky/src/java/se/llbit/chunky/block/Stairs.java
  chunky/src/java/se/llbit/chunky/block/Trapdoor.java
  chunky/src/java/se/llbit/chunky/block/TripwireHook.java
  chunky/src/java/se/llbit/chunky/block/Vine.java
  chunky/src/java/se/llbit/chunky/block/WallSign.java
  chunky/src/java/se/llbit/chunky/block/legacy/LegacyBlockUtils.java
  chunky/src/java/se/llbit/chunky/block/legacy/LegacyBlocks.java
  chunky/src/java/se/llbit/chunky/block/legacy/LegacyBlocksFinalizer.java
  chunky/src/java/se/llbit/chunky/block/legacy/LegacyMinecraftBlockProvider.java
  chunky/src/java/se/llbit/chunky/block/legacy/UnfinalizedLegacyBlock.java
  chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacyBanner.java
  chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacyBed.java
  chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacyChest.java
  chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacyChorusPlant.java
  chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacyCobblestoneWall.java
  chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacyDoorPart.java
  chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacyFence.java
  chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacyFenceGate.java
  chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacyFire.java
  chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacyFlowerPot.java
  chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacyGlassPane.java
  chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacyIronBars.java
  chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacyLargeFlower.java
  chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacyMelonStem.java
  chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacyNetherPortal.java
  chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacyPumpkinStem.java
  chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacyRedstoneWire.java
  chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacySkull.java
  chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacySnowCoverableBlock.java
  chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacyStairs.java
  chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacyTripwire.java
  chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacyVine.java
  chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacyWallBanner.java
  chunky/src/java/se/llbit/chunky/chunk/BlockPalette.java
  chunky/src/java/se/llbit/chunky/entity/SkullEntity.java
  chunky/src/java/se/llbit/chunky/main/Chunky.java
  chunky/src/java/se/llbit/chunky/map/SurfaceLayer.java
  chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
  chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java
  chunky/src/java/se/llbit/chunky/world/BlockData.java
  chunky/src/java/se/llbit/chunky/world/Chunk.java
Labels: feature request, minecraft

#964 Fix overwriting snapshot control having no effect on saving snapshots.
  chunky/src/java/se/llbit/chunky/main/Chunky.java
  chunky/src/java/se/llbit/chunky/renderer/DefaultRenderManager.java
  chunky/src/java/se/llbit/chunky/renderer/RenderManager.java
  chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java
Labels: Plugin API, bug

#967 Add "Dismiss All" to warnings dialog
  chunky/src/java/se/llbit/chunky/ui/ChunkyErrorDialog.java
  chunky/src/res/se/llbit/chunky/ui/ErrorDialog.fxml
  chunky/src/res/se/llbit/chunky/ui/WarningDialog.fxml
Labels: GUI

#979 Prevent map view from attempting to render as fast as possible
  chunky/src/java/se/llbit/chunky/ui/ChunkMap.java
Labels: GUI, performance

#968 Fix paintings with 1.14+ resource packs
  chunky/src/java/se/llbit/chunky/entity/PaintingEntity.java
  chunky/src/java/se/llbit/chunky/resources/Texture.java
  chunky/src/java/se/llbit/chunky/resources/TexturePackLoader.java
  chunky/src/java/se/llbit/chunky/resources/texturepack/PaintingBackTexture.java
  chunky/src/java/se/llbit/chunky/resources/texturepack/PaintingTexture.java
  chunky/src/java/se/llbit/chunky/resources/texturepack/PaintingTextureAdapter.java
  chunky/src/java/se/llbit/chunky/world/material/PaintingMaterial.java
Labels: bug, chunky 2.x, minecraft

#982 Add potted azalea bush and new lit candle textures
  chunky/src/java/se/llbit/chunky/block/Candle.java
  chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
  chunky/src/java/se/llbit/chunky/model/FlowerPotModel.java
  chunky/src/java/se/llbit/chunky/resources/Texture.java
  chunky/src/java/se/llbit/chunky/resources/TexturePackLoader.java
Labels: minecraft

#983 Move none to the top of the post processor combobox and add a separator.
  chunky/src/java/se/llbit/chunky/ui/render/PostprocessingTab.java
Labels: GUI, chunky 2.x

#984 Mark ladders as non-solid
  chunky/src/java/se/llbit/chunky/block/Ladder.java
Labels: bug
