Repository chunky-dev/chunky, pull requests merged in 2022-03, with the labels that each got.

#1172 Feature: UI for locking canvas size aspect ratio
  chunky/src/java/se/llbit/chunky/ui/Icons.java
  chunky/src/java/se/llbit/chunky/ui/elements/SizeInput.java
  chunky/src/java/se/llbit/chunky/ui/render/tabs/GeneralTab.java
  chunky/src/res/se/llbit/chunky/ui/render/tabs/GeneralTab.fxml
  chunky/src/res/style.css
  lib/src/se/llbit/chunky/ui/Adjuster.java
  lib/src/se/llbit/chunky/ui/IntegerAdjuster.java
  lib/src/se/llbit/chunky/ui/IntegerTextField.java
  lib/src/se/llbit/chunky/ui/NumericTextField.java
  lib/src/se/llbit/chunky/ui/ValidatingNumberStringConverter.java
  lib/src/se/llbit/math/ObservableSize2D.java
  lib/src/se/llbit/math/QuickMath.java
  lib/src/se/llbit/math/Size2D.java
  lib/src/se/llbit/math/WritableSize2D.java
Labels: GUI

#1197 Fix empty 16x16x16 sections of identical blocks.
  chunky/src/java/se/llbit/chunky/world/Chunk.java
Labels: bug, minecraft, backport-me

#1192 Add a new setting to choose the aperture shape for custom bokeh
  chunky/src/java/se/llbit/chunky/renderer/ApertureShape.java
  chunky/src/java/se/llbit/chunky/renderer/projection/ApertureProjector.java
  chunky/src/java/se/llbit/chunky/renderer/scene/Camera.java
  chunky/src/java/se/llbit/chunky/ui/render/tabs/CameraTab.java
  chunky/src/res/se/llbit/chunky/renderer/scene/gaussian-aperture.png
  chunky/src/res/se/llbit/chunky/renderer/scene/hexagon-aperture.png
  chunky/src/res/se/llbit/chunky/renderer/scene/pentagon-aperture.png
  chunky/src/res/se/llbit/chunky/renderer/scene/star-aperture.png
  chunky/src/res/se/llbit/chunky/ui/render/tabs/CameraTab.fxml
Labels: renderer, scene format

#1209 Load textures with ImageIO if AWT fails.
  chunky/src/java/se/llbit/resources/ImageLoader.java
Labels: bug, backport-me
