Repository chunky-dev/chunky, pull requests merged in 2022-05, with the labels that each got.

#1255 Update brewing stand model uv coordinates.
  chunky/src/java/se/llbit/chunky/model/BrewingStandModel.java
Labels: minecraft

#1253 Fix broken change scenes directory button
  chunky/src/java/se/llbit/chunky/ui/controller/ChunkyFxController.java
  chunky/src/java/se/llbit/chunky/ui/dialogs/SceneDirectoryPicker.java
  chunky/src/res/se/llbit/chunky/ui/elements/SceneDirectoryChooser.fxml
Labels: bug, GUI

#1261 Move the scenes directory buttons to the scene chooser dialog.
  chunky/src/java/se/llbit/chunky/ui/controller/ChunkyFxController.java
  chunky/src/java/se/llbit/chunky/ui/controller/SceneChooserController.java
  chunky/src/res/se/llbit/chunky/ui/Chunky.fxml
  chunky/src/res/se/llbit/chunky/ui/dialogs/SceneChooser.fxml
Labels: GUI

#1058 Improve UI
  chunky/src/java/se/llbit/chunky/renderer/RenderContext.java
  chunky/src/java/se/llbit/chunky/renderer/SceneIOProvider.java
  chunky/src/java/se/llbit/chunky/renderer/scene/AsynchronousSceneManager.java
  chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
  chunky/src/java/se/llbit/chunky/renderer/scene/SynchronousSceneManager.java
  chunky/src/java/se/llbit/chunky/ui/ChunkMap.java
  chunky/src/java/se/llbit/chunky/ui/ChunkyFx.java
  chunky/src/java/se/llbit/chunky/ui/HyperlinkMenuItem.java
  chunky/src/java/se/llbit/chunky/ui/RenderCanvasFx.java
  chunky/src/java/se/llbit/chunky/ui/controller/ChunkyFxController.java
  chunky/src/java/se/llbit/chunky/ui/controller/CreditsController.java
  chunky/src/java/se/llbit/chunky/ui/controller/RenderControlsFxController.java
  chunky/src/java/se/llbit/chunky/ui/dialogs/Credits.java
  chunky/src/java/se/llbit/chunky/ui/dialogs/ValidatingTextInputDialog.java
  chunky/src/java/se/llbit/chunky/ui/render/tabs/AdvancedTab.java
  chunky/src/java/se/llbit/chunky/ui/render/tabs/GeneralTab.java
  chunky/src/java/se/llbit/chunky/ui/render/tabs/TexturesTab.java
  chunky/src/res/se/llbit/chunky/ui/Chunky.fxml
  chunky/src/res/se/llbit/chunky/ui/dialogs/Credits.fxml
  chunky/src/res/se/llbit/chunky/ui/render/tabs/AdvancedTab.fxml
  chunky/src/res/se/llbit/chunky/ui/render/tabs/TexturesTab.fxml
Labels: GUI

#1103 Headless mode : Allow json parameter in -set option
  chunky/src/java/se/llbit/chunky/main/CommandLineOptions.java
Labels: headless mode

#1285 Tint sugar cane with the grass color.
  chunky/src/java/se/llbit/chunky/block/Fern.java
  chunky/src/java/se/llbit/chunky/block/Grass.java
  chunky/src/java/se/llbit/chunky/block/LargeFern.java
  chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
  chunky/src/java/se/llbit/chunky/block/SugarCane.java
  chunky/src/java/se/llbit/chunky/block/TallGrass.java
  chunky/src/java/se/llbit/chunky/model/GrassTintedSpriteModel.java
Labels: minecraft
