Repository chunky-dev/chunky, pull requests merged in 2022-07, with the labels that each got.

#1329 Use the compacted WorldTexture for 2d biomes by default again
  chunky/src/java/se/llbit/chunky/renderer/scene/biome/BiomeStructure.java
  chunky/src/java/se/llbit/chunky/renderer/scene/biome/Trivial2dBiomeStructure.java
  chunky/src/java/se/llbit/chunky/renderer/scene/biome/Trivial3dBiomeStructure.java
  chunky/src/java/se/llbit/chunky/renderer/scene/biome/WorldTexture2dBiomeStructure.java
  chunky/src/java/se/llbit/chunky/ui/render/tabs/AdvancedTab.java
Labels: performance

#1335 Fix crash if a profile has no skins.
  chunky/src/java/se/llbit/util/mojangapi/MinecraftSkin.java
Labels: bug, snapshot-only

#1339 Download skins of heads that only have a skull owner but no embedded skin
  chunky/src/java/se/llbit/chunky/entity/PlayerEntity.java
  chunky/src/test/se/llbit/chunky/block/SkullTextureTest.java
Labels: minecraft

#1338 Use HeadEntity primitives for armor stand heads.
  chunky/src/java/se/llbit/chunky/entity/ArmorStand.java
  chunky/src/java/se/llbit/chunky/entity/HeadEntity.java
  chunky/src/java/se/llbit/chunky/entity/PlayerEntity.java
  chunky/src/java/se/llbit/chunky/entity/SkullEntity.java
Labels: backport-me

#1351 Add more labels to camera controls
  chunky/src/java/se/llbit/chunky/ui/elements/TextFieldLabelWrapper.java
  chunky/src/java/se/llbit/chunky/ui/render/tabs/CameraTab.java
  chunky/src/res/se/llbit/chunky/ui/render/tabs/CameraTab.fxml
  chunky/src/res/style.css
Labels: GUI

#1362 Throw exception when failing to load a chunk, allowing it to be safely skipped
  chunky/src/java/se/llbit/chunky/chunk/ChunkLoadingException.java
  chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
  chunky/src/java/se/llbit/chunky/world/Chunk.java
  chunky/src/java/se/llbit/chunky/world/region/MCRegion.java
Labels: world-loading

#1385 Sort materials list
  chunky/src/java/se/llbit/chunky/ui/render/tabs/MaterialsTab.java
Labels: GUI

#1374 Update entity and camera location controls
  chunky/src/java/se/llbit/chunky/ui/render/tabs/EntitiesTab.java
  chunky/src/res/se/llbit/chunky/ui/render/tabs/EntitiesTab.fxml
Labels: GUI

#1377 Add viewport lines to camera preset icons
  chunky/src/res/icons/iso-ne.png
  chunky/src/res/icons/iso-nw.png
  chunky/src/res/icons/iso-se.png
  chunky/src/res/icons/iso-sw.png
Labels: GUI

#1371 Add entity position fields to allow user to position the entity
  chunky/src/java/se/llbit/chunky/ui/render/tabs/EntitiesTab.java
  chunky/src/res/se/llbit/chunky/ui/render/tabs/EntitiesTab.fxml
Labels: GUI

#1361 Only update the map selection if the user loads the world associated with a scene
  chunky/src/java/se/llbit/chunky/ui/controller/ChunkyFxController.java
Labels: backport-me, world-loading

#1404 Fix head entity x/z position.
  chunky/src/java/se/llbit/chunky/entity/HeadEntity.java
Labels: bug, backport-me
