Repository chunky-dev/chunky, pull requests merged in 2022-10, with the labels that each got.

#1442 Add Loading scenes list title to inform user
  chunky/src/java/se/llbit/chunky/ui/controller/ChunkyFxController.java
  chunky/src/java/se/llbit/chunky/ui/controller/SceneChooserController.java
  chunky/src/java/se/llbit/chunky/ui/dialogs/SceneChooser.java
Labels: GUI

#1447 Fix single color textures not working with biome colors
  chunky/src/java/se/llbit/chunky/model/AABBModel.java
  chunky/src/java/se/llbit/chunky/model/AnimatedQuadModel.java
  chunky/src/java/se/llbit/chunky/model/QuadModel.java
  chunky/src/java/se/llbit/chunky/model/Tint.java
  chunky/src/java/se/llbit/chunky/ui/render/tabs/TexturesTab.java
Labels: bug

#1448 Add scene refresh event plugin API.
  chunky/src/java/se/llbit/chunky/renderer/SceneProvider.java
  chunky/src/java/se/llbit/chunky/renderer/scene/AsynchronousSceneManager.java
  chunky/src/java/se/llbit/chunky/renderer/scene/SceneManager.java
  chunky/src/java/se/llbit/chunky/renderer/scene/SynchronousSceneManager.java
  chunky/src/test/se/llbit/chunky/main/PluginApiTest.java
  chunky/src/test/se/llbit/chunky/renderer/MockSceneProvider.java
Labels: Plugin API, hacktoberfest-accepted

#1451 Add context menu transformers for map and render view.
  chunky/src/java/se/llbit/chunky/main/Chunky.java
  chunky/src/java/se/llbit/chunky/plugin/ContextMenuTransformer.java
  chunky/src/java/se/llbit/chunky/ui/ChunkMap.java
  chunky/src/java/se/llbit/chunky/ui/RenderCanvasFx.java
Labels: Plugin API, hacktoberfest-accepted

#1462 Add an `Apparent sky brightness` control
  chunky/src/java/se/llbit/chunky/renderer/scene/PreviewRayTracer.java
  chunky/src/java/se/llbit/chunky/renderer/scene/Sky.java
  chunky/src/java/se/llbit/chunky/ui/render/tabs/LightingTab.java
  chunky/src/res/se/llbit/chunky/ui/render/tabs/LightingTab.fxml
Labels: hacktoberfest-accepted

#1450 Resize `Settings Export` Box. Add `Select All` button.
  chunky/src/java/se/llbit/chunky/ui/dialogs/SettingsExport.java
  chunky/src/java/se/llbit/fxutil/ColumnsBoxBuilder.java
Labels: GUI, hacktoberfest-accepted

#1458 Reorganize `Scene` tab and add `<Separator />`s to the `Lighting` and `Sky & Fog` tabs
  chunky/src/java/se/llbit/chunky/ui/render/tabs/GeneralTab.java
  chunky/src/res/se/llbit/chunky/ui/render/tabs/GeneralTab.fxml
  chunky/src/res/se/llbit/chunky/ui/render/tabs/HelpTab.fxml
  chunky/src/res/se/llbit/chunky/ui/render/tabs/LightingTab.fxml
  chunky/src/res/se/llbit/chunky/ui/render/tabs/SkyTab.fxml
Labels: GUI, hacktoberfest-accepted

#1456 Automatically hide and collapse `Water` tab panels
  chunky/src/java/se/llbit/chunky/ui/render/tabs/WaterTab.java
  chunky/src/res/se/llbit/chunky/ui/render/tabs/SkyTab.fxml
  chunky/src/res/se/llbit/chunky/ui/render/tabs/WaterTab.fxml
Labels: GUI, hacktoberfest-accepted

#1468 Improve skymap and other error logging.
  chunky/src/java/se/llbit/chunky/renderer/projection/ApertureProjector.java
  chunky/src/java/se/llbit/chunky/renderer/scene/AsynchronousSceneManager.java
  chunky/src/java/se/llbit/chunky/renderer/scene/Sky.java
  chunky/src/java/se/llbit/chunky/resources/HDRTexture.java
  chunky/src/java/se/llbit/chunky/resources/PFMTexture.java
Labels: hacktoberfest-accepted

#1459 Increase the range of cloud offset sliders and change default cloud size
  chunky/src/java/se/llbit/chunky/renderer/scene/Sky.java
  chunky/src/java/se/llbit/chunky/ui/render/tabs/SkyTab.java
Labels: hacktoberfest-accepted

#1473 Add pitch and roll rotation for skymap and skyboxes.
  chunky/src/java/se/llbit/chunky/renderer/scene/Sky.java
  chunky/src/java/se/llbit/chunky/ui/render/settings/SkyboxSettings.java
  chunky/src/java/se/llbit/chunky/ui/render/settings/SkymapSettings.java
  chunky/src/java/se/llbit/math/Matrix3.java
  chunky/src/res/se/llbit/chunky/ui/render/settings/SkyboxSettings.fxml
  chunky/src/res/se/llbit/chunky/ui/render/settings/SkymapSettings.fxml
Labels: hacktoberfest-accepted

#1480 Add vertically stacked omni-directional stereo projector
  chunky/src/java/se/llbit/chunky/renderer/projection/ProjectionMode.java
  chunky/src/java/se/llbit/chunky/renderer/projection/stereo/ODSSinglePerspectiveProjector.java
  chunky/src/java/se/llbit/chunky/renderer/projection/stereo/ODSVerticalStackedProjector.java
  chunky/src/java/se/llbit/chunky/renderer/projection/stereo/OmniDirectionalStereoProjector.java
  chunky/src/java/se/llbit/chunky/renderer/scene/Camera.java
Labels: hacktoberfest-accepted

#1474 Add a `Sky exposure` control, fix the `Draw sun` control disabling sunlight, and add few new sun controls
  chunky/src/java/se/llbit/chunky/renderer/scene/PathTracer.java
  chunky/src/java/se/llbit/chunky/renderer/scene/Sky.java
  chunky/src/java/se/llbit/chunky/renderer/scene/Sun.java
  chunky/src/java/se/llbit/chunky/ui/render/tabs/LightingTab.java
  chunky/src/res/se/llbit/chunky/ui/render/tabs/LightingTab.fxml
Labels: renderer, hacktoberfest-accepted

#1492 Add a `Metalness` control for beacon beams
  chunky/src/java/se/llbit/chunky/ui/render/tabs/EntitiesTab.java
  chunky/src/java/se/llbit/chunky/world/material/BeaconBeamMaterial.java
Labels: GUI

#1495 Log unknown biome warning as info with the logger and remove debug output.
  chunky/src/java/se/llbit/chunky/chunk/biome/GenericQuartBiomeData3d.java
  chunky/src/java/se/llbit/chunky/ui/dialogs/ValidatingTextInputDialog.java
  chunky/src/java/se/llbit/chunky/world/model/JsonModel.java
Labels: backport-me
