Repository chunky-dev/chunky, pull requests merged in 2022-01, with the labels that each got.

#1114 Show a warning in the launcher when not using a 64-bit JVM
  launcher/src/se/llbit/chunky/launcher/ChunkyDeployer.java
  launcher/src/se/llbit/chunky/launcher/ChunkyLauncher.java
  launcher/src/se/llbit/chunky/launcher/JreUtil.java
  launcher/src/se/llbit/chunky/launcher/ui/ChunkyLauncherController.java
  lib/src/se/llbit/chunky/launcher/LauncherSettings.java
Labels: java problem, launcher

#1015 Scene Picker UI: Cleanup & Sort By Last Modified
  chunky/src/java/se/llbit/chunky/ui/SceneChooser.java
  chunky/src/java/se/llbit/chunky/ui/SceneChooserController.java
  chunky/src/res/se/llbit/chunky/ui/SceneChooser.fxml
Labels: GUI

#1085 1.18 Biome Support through BiomePalette
  chunky/src/java/se/llbit/chunky/map/BiomeLayer.java
  chunky/src/java/se/llbit/chunky/map/SurfaceLayer.java
  chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
  chunky/src/java/se/llbit/chunky/resources/texturepack/FoliageColorTexture.java
  chunky/src/java/se/llbit/chunky/resources/texturepack/GrassColorTexture.java
  chunky/src/java/se/llbit/chunky/world/Biomes.java
  chunky/src/java/se/llbit/chunky/world/Chunk.java
  chunky/src/java/se/llbit/chunky/world/EmptyChunk.java
  chunky/src/java/se/llbit/chunky/world/EmptyRegionChunk.java
  chunky/src/java/se/llbit/chunky/world/ImposterCubicChunk.java
  chunky/src/java/se/llbit/chunky/world/biome/ArrayBiomePalette.java
  chunky/src/java/se/llbit/chunky/world/biome/Biome.java
  chunky/src/java/se/llbit/chunky/world/biome/BiomePalette.java
  chunky/src/java/se/llbit/chunky/world/biome/Biomes.java
  chunky/src/java/se/llbit/chunky/world/biome/MapBiomePalette.java
  chunky/src/java/se/llbit/math/ColorUtil.java
Labels: minecraft, backport-me

#1132 Fix missing smooth stone slab texture when using <1.14 resourcepacks.
  chunky/src/java/se/llbit/chunky/resources/Texture.java
  chunky/src/java/se/llbit/chunky/resources/TexturePackLoader.java
Labels: bug, textures, backport-me

#1141 Fix sign texture with pre-1.14 resourcepacks.
  chunky/src/java/se/llbit/chunky/resources/Texture.java
  chunky/src/java/se/llbit/chunky/resources/TexturePackLoader.java
Labels: bug, textures, backport-me

#1143 Fix crash due to ui being updated on the wrong thread after loading a scene.
  chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java
Labels: backport-me

#1146 Fix grass block being non-solid.
  chunky/src/java/se/llbit/chunky/block/GrassBlock.java
Labels: bug, snapshot-only

#1134 Draft: Backport 1.18 support
  chunky/src/java/se/llbit/chunky/chunk/ChunkData.java
  chunky/src/java/se/llbit/chunky/chunk/EmptyChunkData.java
  chunky/src/java/se/llbit/chunky/chunk/GenericChunkData.java
  chunky/src/java/se/llbit/chunky/chunk/SimpleChunkData.java
  chunky/src/java/se/llbit/chunky/chunk/biome/BiomeData.java
  chunky/src/java/se/llbit/chunky/chunk/biome/BiomeData2d.java
  chunky/src/java/se/llbit/chunky/chunk/biome/BiomeDataFactory.java
  chunky/src/java/se/llbit/chunky/chunk/biome/GenericQuartBiomeData3d.java
  chunky/src/java/se/llbit/chunky/chunk/biome/QuartBiomeData3d.java
  chunky/src/java/se/llbit/chunky/chunk/biome/UnknownBiomeData.java
  chunky/src/java/se/llbit/chunky/map/BiomeLayer.java
  chunky/src/java/se/llbit/chunky/map/SurfaceLayer.java
  chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
  chunky/src/java/se/llbit/chunky/resources/texturepack/FoliageColorTexture.java
  chunky/src/java/se/llbit/chunky/resources/texturepack/GrassColorTexture.java
  chunky/src/java/se/llbit/chunky/world/Biomes.java
  chunky/src/java/se/llbit/chunky/world/Chunk.java
  chunky/src/java/se/llbit/chunky/world/CubicWorld.java
  chunky/src/java/se/llbit/chunky/world/EmptyChunk.java
  chunky/src/java/se/llbit/chunky/world/EmptyRegionChunk.java
  chunky/src/java/se/llbit/chunky/world/ImposterCubicChunk.java
  chunky/src/java/se/llbit/chunky/world/World.java
  chunky/src/java/se/llbit/chunky/world/biome/ArrayBiomePalette.java
  chunky/src/java/se/llbit/chunky/world/biome/Biome.java
  chunky/src/java/se/llbit/chunky/world/biome/BiomePalette.java
  chunky/src/java/se/llbit/chunky/world/biome/Biomes.java
  chunky/src/java/se/llbit/chunky/world/biome/MapBiomePalette.java
  chunky/src/java/se/llbit/chunky/world/region/RegionParser.java
  chunky/src/java/se/llbit/math/ColorUtil.java
  chunky/src/java/se/llbit/util/NbtUtil.java
  chunky/src/java/se/llbit/util/NotNull.java
  chunky/src/java/se/llbit/util/annotation/Nullable.java
Labels: minecraft

#1153 Fix badlands and roofed forest biome colors
  chunky/src/java/se/llbit/chunky/world/biome/Biomes.java
Labels: bug, backport-me

#1158 Gamma correct tint colors.
  chunky/src/java/se/llbit/chunky/model/Tint.java
Labels: bug, renderer, snapshot-only
