Repository chunky-dev/chunky, pull requests merged in 2022-08, with the labels that each got.

#1383 Fix initial text overflow for labeled text fields by scrolling to the end
  chunky/src/java/se/llbit/chunky/ui/elements/TextFieldLabelWrapper.java
Labels: GUI

#1418 Allow for input fields to have their own precision & set fog precision to 6 decimal places
  chunky/src/java/se/llbit/chunky/ui/render/tabs/SkyTab.java
  lib/src/se/llbit/chunky/ui/Adjuster.java
  lib/src/se/llbit/chunky/ui/ValidatingNumberStringConverter.java
Labels: GUI

#1417 Fix scene zip export.
  chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
  chunky/src/java/se/llbit/util/ZipExport.java
Labels: snapshot-only

#1421 Fix horizon offset being dropped when render starts.
  chunky/src/java/se/llbit/chunky/renderer/scene/Sky.java
Labels: backport-me

#1422 Fix icon size of the delete selected chunks icon for larget resource packs.
  chunky/src/java/se/llbit/chunky/ui/ChunkMap.java
Labels: backport-me

#1424 Fix sky mode settings not being shown after loading a scene.
  chunky/src/java/se/llbit/chunky/ui/render/tabs/SkyTab.java
Labels: backport-me

#1423 Fix preview render grid not being aligned to chunks.
  chunky/src/java/se/llbit/chunky/renderer/scene/PreviewRayTracer.java
Labels: backport-me

#1427 Change y clipping labels to make them more clear.
  chunky/src/res/se/llbit/chunky/ui/Chunky.fxml
  chunky/src/res/se/llbit/chunky/ui/render/tabs/GeneralTab.fxml
Labels: GUI

#1436 Fix loading and saving scenes without loaded chunks.
  chunky/src/java/se/llbit/chunky/resources/OctreeFileFormat.java
Labels: bug, snapshot-only

#1438 Fix loading empty chunks.
  chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
  chunky/src/java/se/llbit/chunky/world/Chunk.java
Labels: bug
