Repository chunky-dev/chunky, pull requests merged in 2022-02, with the labels that each got.

#1159 Sort worlds by last modified time.
  chunky/src/java/se/llbit/chunky/ui/SceneChooserController.java
  chunky/src/java/se/llbit/chunky/ui/TableSortConfigSerializer.java
  chunky/src/java/se/llbit/chunky/ui/WorldChooserController.java
  chunky/src/java/se/llbit/chunky/world/World.java
  chunky/src/res/se/llbit/chunky/ui/WorldChooser.fxml
  lib/src/se/llbit/chunky/PersistentSettings.java
Labels: GUI, backport-me

#1168 Set the y-clip slider ranges properly when loading a world.
  chunky/src/java/se/llbit/chunky/ui/render/GeneralTab.java
Labels: GUI

#1181 Select the correct Chunky version after updating in the launcher.
  launcher/src/se/llbit/chunky/launcher/ui/UpdateDialogController.java
Labels: bug, launcher

#1169 Make load world confirmation always on top.
  chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java
  chunky/src/java/se/llbit/chunky/ui/WorldChooserController.java
  chunky/src/java/se/llbit/fxutil/Dialogs.java
Labels: GUI, backport-me

#1166 Fix not updating gui tabs on chunk load/reload
  chunky/src/java/se/llbit/chunky/ui/RenderControlsFxController.java
Labels: bug, GUI, backport-me

#1174 Fix map selection of invalid chunks.
  chunky/src/java/se/llbit/chunky/map/MapTile.java
Labels: bug, GUI, backport-me
