Repository chunky-dev/chunky, pull requests merged in 2022-12, with the labels that each got.

#1508 Potential fix for clipping with parallel projection and transparent sky.
  chunky/src/java/se/llbit/chunky/renderer/projection/ParallelProjector.java
  chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
Labels: backport-me

#1510 De-duplicate scene saving code to ensure onSceneSaved is always called.
  chunky/src/java/se/llbit/chunky/renderer/scene/SceneManager.java
  chunky/src/java/se/llbit/chunky/renderer/scene/SynchronousSceneManager.java
Labels: bug, GUI, snapshot-only

#1514 Carry energy through specular reflection, metallic reflection, and transmission.
  chunky/src/java/se/llbit/chunky/renderer/scene/PathTracer.java
Labels: bug, renderer
