Repository chunky-dev/chunky, pull requests merged in 2023-03, with the labels that each got.

#1557 Add an API to get the canvas / map coordinate in the context menu callback.
  chunky/src/java/se/llbit/chunky/main/Chunky.java
  chunky/src/java/se/llbit/chunky/ui/ChunkMap.java
  chunky/src/java/se/llbit/chunky/ui/RenderCanvasFx.java
Labels: Plugin API

#1566 Fix camera renaming cloning the camera
  chunky/src/java/se/llbit/chunky/ui/render/tabs/CameraTab.java
Labels: bug, GUI, backport-me

#1567 Fix jukebox side texture.
  chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
  chunky/src/java/se/llbit/chunky/resources/Texture.java
  chunky/src/java/se/llbit/chunky/resources/TexturePackLoader.java
Labels: minecraft, backport-me
