Repository chunky-dev/chunky, pull requests merged in 2023-01, with the labels that each got.

#1292 Add a simple JavaFX installer to the launcher.
  launcher/src/se/llbit/chunky/launcher/ChunkyLauncher.java
  launcher/src/se/llbit/chunky/launcher/JavaFxDownloads.java
  launcher/src/se/llbit/chunky/launcher/JavaFxInstaller.java
  launcher/src/se/llbit/chunky/launcher/JavaFxLocator.java
Labels: java problem, launcher

#1518 Reduce size of light block model
  chunky/src/java/se/llbit/chunky/block/LightBlock.java
  chunky/src/java/se/llbit/chunky/chunk/BlockPalette.java
  chunky/src/java/se/llbit/chunky/model/LightBlockModel.java
Labels: renderer, backport-me

#1478 More details in error messages in MCA chunk loading
  chunky/src/java/se/llbit/chunky/world/ChunkDataSource.java
  chunky/src/java/se/llbit/chunky/world/region/ChunkReadException.java
  chunky/src/java/se/llbit/chunky/world/region/MCRegion.java
  chunky/src/java/se/llbit/chunky/world/region/Region.java
Labels: hacktoberfest-accepted

#1461 Add `Select chunks in radius` button, with configuration menu
  chunky/src/java/se/llbit/chunky/ui/ChunkMap.java
  chunky/src/java/se/llbit/chunky/ui/dialogs/SelectChunksInRadiusDialog.java
  chunky/src/java/se/llbit/chunky/world/ChunkSelectionTracker.java
Labels: hacktoberfest-accepted

#1486 Remove chunk delete UI
  chunky/src/java/se/llbit/chunky/ui/ChunkMap.java
  chunky/src/java/se/llbit/chunky/ui/controller/ChunkyFxController.java
  chunky/src/java/se/llbit/chunky/world/DeleteChunksJob.java
Labels: hacktoberfest-accepted

#1504 Add render region mode.
  chunky/src/java/se/llbit/chunky/renderer/PathTracingRenderer.java
  chunky/src/java/se/llbit/chunky/renderer/PreviewRenderer.java
  chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
  chunky/src/java/se/llbit/chunky/ui/elements/SizeInput.java
  chunky/src/java/se/llbit/chunky/ui/render/tabs/GeneralTab.java
  chunky/src/res/se/llbit/chunky/ui/render/tabs/GeneralTab.fxml
  lib/src/se/llbit/math/QuickMath.java
Labels: GUI, renderer

#1538 Don't apply sky fog if fog mode is uniform and density is 0.
  chunky/src/java/se/llbit/chunky/renderer/scene/Fog.java
Labels: snapshot-only

#1536 Backport entity regions support
  chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
  chunky/src/java/se/llbit/chunky/world/Chunk.java
  chunky/src/java/se/llbit/chunky/world/region/MCRegion.java
Labels: minecraft
