Repository chunky-dev/chunky, pull requests merged in 2023-06, with the labels that each got.

#1598 Fix wall sign dimension and position.
  chunky/src/java/se/llbit/chunky/entity/WallSignEntity.java
Labels: bug, minecraft, backport-me

#1587 Use a constant multiplier on `Parallel` projection
  chunky/src/java/se/llbit/chunky/renderer/scene/Camera.java
Labels: GUI

#1592 Add support for font file references to support 1.20 fonts and back-side sign texts.
  chunky/src/java/se/llbit/chunky/entity/SignEntity.java
  chunky/src/java/se/llbit/chunky/entity/WallSignEntity.java
  chunky/src/java/se/llbit/chunky/resources/SignTexture.java
  chunky/src/java/se/llbit/chunky/resources/texturepack/JsonFontTextureLoader.java
Labels: textures, minecraft
