Repository chunky-dev/chunky, pull requests merged in 2023-10, with the labels that each got.

#1641 Ensure the common thread pool has at least 2 threads.
  chunky/src/java/se/llbit/chunky/main/Chunky.java
Labels: backport-me

#1626 Add dyed signs.
  chunky/src/java/se/llbit/chunky/entity/HangingSignEntity.java
  chunky/src/java/se/llbit/chunky/entity/SignEntity.java
  chunky/src/java/se/llbit/chunky/entity/WallHangingSignEntity.java
  chunky/src/java/se/llbit/chunky/entity/WallSignEntity.java
  chunky/src/java/se/llbit/chunky/resources/SignTexture.java
Labels: minecraft

#1640 Small tasktracker improvments.
  chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
  chunky/src/java/se/llbit/chunky/resources/OctreeFileFormat.java
  chunky/src/java/se/llbit/util/TaskTracker.java
Labels: hacktoberfest-accepted

#1643 Add piglin heads.
  chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
  chunky/src/java/se/llbit/chunky/block/minecraft/Head.java
  chunky/src/java/se/llbit/chunky/block/minecraft/WallHead.java
  chunky/src/java/se/llbit/chunky/entity/PlayerEntity.java
  chunky/src/java/se/llbit/chunky/entity/SkullEntity.java
  chunky/src/java/se/llbit/chunky/entity/UVMapHelper.java
  chunky/src/java/se/llbit/chunky/resources/Texture.java
Labels: minecraft

#1649 Fix TIFF format export
  chunky/src/java/se/llbit/chunky/renderer/export/Tiff32ExportFormat.java
  chunky/src/java/se/llbit/imageformats/tiff/TiffFileWriter.java
Labels: bug, hacktoberfest-accepted, backport-me

#1648 Add a dropdown field to select the entity type that is being added.
  chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
  chunky/src/java/se/llbit/chunky/ui/render/tabs/EntitiesTab.java
  chunky/src/res/se/llbit/chunky/ui/render/tabs/EntitiesTab.fxml
Labels: GUI, hacktoberfest-accepted

#1656 Add sha256 support for library verification to the launcher and a flag to disable it.
  chunky/src/java/se/llbit/chunky/main/CommandLineOptions.java
  launcher/src/se/llbit/chunky/launcher/ChunkyDeployer.java
  launcher/src/se/llbit/chunky/launcher/ChunkyLauncher.java
  launcher/src/se/llbit/chunky/launcher/VersionInfo.java
  launcher/src/se/llbit/chunky/launcher/ui/UpdateDialogController.java
  lib/src/se/llbit/chunky/launcher/LauncherSettings.java
  lib/src/se/llbit/util/Util.java
  releasetools/src/releasetools/ReleaseBuilder.java
Labels: launcher

#1433 Use the available physical memory as upper memory limit for the slider in the launcher.
  launcher/src/se/llbit/chunky/launcher/ui/ChunkyLauncherController.java
Labels: launcher

#1658 Prevent locking camera from resetting render
  chunky/src/java/se/llbit/chunky/renderer/scene/Camera.java
  chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
Labels: hacktoberfest-accepted
