Repository chunky-dev/chunky, pull requests merged in 2024-08, with the labels that each got.

#1743 Fix waterlogged barrier blocks causing ALL air to become water
  chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
Labels: bug, world-loading

#1746 Fix azalea leaves and cherry leaves ignoring material properties.
  chunky/src/java/se/llbit/chunky/block/UntintedLeaves.java
Labels: bug

#1750 Fix build issues on windows due to azul not including JFX on windows
  launcher/build.gradle
  lib/build.gradle
Labels: java problem

#1751 Fix emitters with emitter sampling.
  chunky/src/java/se/llbit/chunky/renderer/scene/PathTracer.java
Labels: bug, renderer, snapshot-only
