Repository chunky-dev/chunky, pull requests merged in 2024-09, with the labels that each got.

#1756 Fix duplicating camera not saving new camera preset
  chunky/src/java/se/llbit/chunky/ui/render/tabs/CameraTab.java
Labels: bug

#1760 Fix loading custom player head textures in 1.21 worlds.
  chunky/src/java/se/llbit/chunky/block/minecraft/Head.java
Labels: minecraft

#1762 Add new cocoa model
  chunky/src/java/se/llbit/chunky/block/minecraft/Cocoa.java
  chunky/src/java/se/llbit/chunky/model/minecraft/CocoaPlantModel.java
  chunky/src/java/se/llbit/chunky/model/minecraft/CocoaPlantModel119.java
Labels: backport-me

#1774 Rename `...` buttons to `Browse`
  launcher/src/se/llbit/chunky/launcher/ui/ChunkyLauncher.fxml
Labels: launcher, GUI

#1771 Show time elapsed for all tasks and use Duration for the duration and eta.
  chunky/src/java/se/llbit/chunky/renderer/ConsoleProgressListener.java
  chunky/src/java/se/llbit/chunky/renderer/DefaultRenderManager.java
  chunky/src/java/se/llbit/chunky/renderer/PreviewRenderer.java
  chunky/src/java/se/llbit/chunky/ui/controller/ChunkyFxController.java
  chunky/src/java/se/llbit/util/ProgressListener.java
  chunky/src/java/se/llbit/util/TaskTracker.java
  chunky/src/test/se/llbit/chunky/renderer/renderdump/RenderDumpTest.java
Labels: GUI

#1466 Fix ChunkDataVersion issues with third party applications
  chunky/src/java/se/llbit/chunky/world/Chunk.java
  chunky/src/java/se/llbit/chunky/world/CubicDimension.java
  chunky/src/java/se/llbit/chunky/world/Dimension.java
  chunky/src/java/se/llbit/chunky/world/ImposterCubicChunk.java
Labels: bug, minecraft, hacktoberfest-accepted
